package lounges

// staticData holds curated lounge data for the top-30 hub airports.
// Cards use the same name conventions as preferences.LoungeCards so
// AnnotateAccess can match them without fuzzy logic.
//
// Sources: Priority Pass directory, LoungeKey directory, airport operator
// websites, and published lounge reviews (2024–2025 data).
var staticData = map[string][]staticLounge{
	// ── Europe ──────────────────────────────────────────────────────────────
	"HEL": {
		// Priority Pass network lounges
		{
			Name:      "Aspire Lounge (Gate 13)",
			Terminal:  "Terminal 2, Schengen, Gate 13",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar", "Newspapers"},
			OpenHours: "05:00–09:00",
		},
		{
			Name:      "Aspire Lounge (Gate 27)",
			Terminal:  "Terminal 2, Schengen, Gate 27",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Newspapers"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 2, Non-Schengen",
			Cards:     merge(ppDragon, amexPlatinum),
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–19:30",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "Finnair Premium Lounge (Schengen)",
			Terminal:  "Terminal 2, Gate 22",
			Cards:     []string{"Finnair Plus Gold", "Finnair Plus Platinum", "Oneworld Sapphire", "Oneworld Emerald", "Finnair Business Class"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Sauna"},
			OpenHours: "04:30–23:00",
		},
		{
			Name:      "Finnair Premium Lounge (Non-Schengen)",
			Terminal:  "Terminal 2, Gate 36",
			Cards:     []string{"Finnair Plus Gold", "Finnair Plus Platinum", "Oneworld Sapphire", "Oneworld Emerald", "Finnair Business Class"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–23:30",
		},
		// Bank-specific lounges
		{
			Name:      "OP Lounge",
			Terminal:  "Terminal 2, Schengen",
			Cards:     []string{"OP Visa Platinum", "OP Private Banking"},
			Amenities: []string{"Wi-Fi", "Snacks", "Coffee", "Newspapers", "Workstations"},
			OpenHours: "05:30–20:00",
		},
	},
	"LHR": {
		{
			Name:      "No1 Lounge",
			Terminal:  "Terminal 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers", "Spa treatments"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "No1 Lounge",
			Terminal:  "Terminal 5",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "Club Aspire Lounge",
			Terminal:  "Terminal 5",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "04:30–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 4",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "06:00–22:00",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "British Airways Galleries First",
			Terminal:  "Terminal 5",
			Cards:     []string{"BA First Class", "Oneworld Emerald", "BA Gold"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Spa"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "British Airways Galleries Club",
			Terminal:  "Terminal 5",
			Cards:     []string{"BA Business Class", "Oneworld Sapphire", "Oneworld Emerald", "BA Silver", "BA Gold"},
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers", "Workstations"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "Virgin Atlantic Clubhouse",
			Terminal:  "Terminal 3",
			Cards:     []string{"Virgin Upper Class", "Virgin Gold"},
			Amenities: []string{"Wi-Fi", "Restaurant", "Cocktail bar", "Spa", "Pool table", "Showers"},
			OpenHours: "05:30–22:00",
		},
		// Amex Centurion Lounge
		{
			Name:      "The Centurion Lounge",
			Terminal:  "Terminal 3",
			Cards:     amexCenturion,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "06:00–22:00",
		},
	},
	"CDG": {
		{
			Name:      "Salon des Lumières (Air France)",
			Terminal:  "Terminal 2E, Hall L",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "Salon Opéra (Air France)",
			Terminal:  "Terminal 2F",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–22:30",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 2E, Hall M",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "No1 Lounges CDG",
			Terminal:  "Terminal 2G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:00",
		},
		// Air France airline lounges (NOT Priority Pass)
		{
			Name:      "Air France Business Lounge",
			Terminal:  "Terminal 2E, Hall L",
			Cards:     []string{"Air France Business Class", "SkyTeam Elite Plus", "Flying Blue Gold", "Flying Blue Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Champagne bar", "Showers", "Workstations"},
			OpenHours: "05:30–23:00",
		},
		{
			Name:      "Air France La Première Lounge",
			Terminal:  "Terminal 2E, Hall L",
			Cards:     []string{"Air France First Class", "Flying Blue Ultimate"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Spa", "Private suites"},
			OpenHours: "06:00–23:00",
		},
		// Amex Centurion Lounge (opened 2024)
		{
			Name:      "The Centurion Lounge",
			Terminal:  "Terminal 2E",
			Cards:     amexCenturion,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
	},
	"FRA": {
		{
			Name:      "Lufthansa Business Lounge",
			Terminal:  "Terminal 1, Pier B",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "Lufthansa Senator Lounge",
			Terminal:  "Terminal 1, Pier Z",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa"},
			OpenHours: "05:30–21:30",
		},
		{
			Name:      "Lufthansa Business Lounge",
			Terminal:  "Terminal 2, Pier D",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 1, Pier A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		// Lufthansa airline lounges (status-only, NOT Priority Pass)
		{
			Name:      "Lufthansa Senator Lounge",
			Terminal:  "Terminal 1, Concourse B",
			Cards:     []string{"Lufthansa First Class", "Lufthansa Business Class", "Star Alliance Gold", "Miles & More Senator", "Miles & More HON Circle"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Sleeping chairs", "Workstations"},
			OpenHours: "05:15–22:00",
		},
		{
			Name:      "Lufthansa Business Lounge (Pier A)",
			Terminal:  "Terminal 1, Pier A",
			Cards:     []string{"Lufthansa Business Class", "Star Alliance Gold", "Miles & More Senator", "Miles & More HON Circle", "Miles & More Frequent Traveller"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Workstations"},
			OpenHours: "05:15–22:00",
		},
		{
			Name:      "Lufthansa First Class Terminal",
			Terminal:  "Terminal 1, separate building",
			Cards:     []string{"Lufthansa First Class", "Miles & More HON Circle"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Cigar lounge", "Showers", "Bath", "Personal assistant", "Porsche transfer"},
			OpenHours: "05:00–22:00",
		},
	},
	"AMS": {
		{
			Name:      "Aspire Lounge (Schengen)",
			Terminal:  "Lounge 4, Pier F",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Aspire Lounge (Non-Schengen)",
			Terminal:  "Lounge 52, Pier G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "No1 Lounge Schiphol",
			Terminal:  "Main Terminal, Non-Schengen",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–21:30",
		},
	},
	"MUC": {
		{
			Name:      "Lufthansa Business Lounge",
			Terminal:  "Terminal 2, Level 04",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Lufthansa Senator Lounge",
			Terminal:  "Terminal 2, Level 04",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa"},
			OpenHours: "05:30–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 1, Module D",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:30",
		},
	},
	"ZRH": {
		{
			Name:      "SWISS Business Lounge",
			Terminal:  "Terminal E (Airside Center)",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		{
			Name:      "SWISS First Class Lounge",
			Terminal:  "Terminal E (Airside Center)",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa"},
			OpenHours: "06:00–21:30",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "05:00–21:00",
		},
	},
	"VIE": {
		{
			Name:      "Austrian Airlines Business Lounge",
			Terminal:  "Terminal F, Gate F04",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal C",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar"},
			OpenHours: "05:00–21:30",
		},
		{
			Name:      "Sky Lounge Vienna",
			Terminal:  "Terminal G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–21:00",
		},
	},
	"FCO": {
		{
			Name:      "Sala Partenze (Alitalia/ITA)",
			Terminal:  "Terminal 1",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:30–21:30",
		},
		{
			Name:      "Sala Laghi",
			Terminal:  "Terminal 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Sala Gioia",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "05:00–21:00",
		},
	},
	"MXP": {
		{
			Name:      "Malpensa Premium Lounge",
			Terminal:  "Terminal 1, Landside",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "04:30–22:30",
		},
		{
			Name:      "Sala Monteverdi",
			Terminal:  "Terminal 1, Airside",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:30",
		},
	},
	"MAD": {
		{
			Name:      "Iberia VIP Lounge",
			Terminal:  "Terminal 4, Level 3",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "Sala VIP Barcelona (Globalia)",
			Terminal:  "Terminal 4",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:30–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 4S",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "06:00–21:00",
		},
	},
	"BCN": {
		{
			Name:      "Sala VIP Barcelona",
			Terminal:  "Terminal 1, Level 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		{
			Name:      "Sala Ágora",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "06:00–21:30",
		},
	},
	"CPH": {
		{
			Name:      "SAS Lounge Copenhagen",
			Terminal:  "Terminal 2, Gate C",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:30",
		},
		{
			Name:      "No1 Lounge Copenhagen",
			Terminal:  "Terminal 2, Pier C",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–21:00",
		},
	},
	"OSL": {
		{
			Name:      "SAS Lounge Oslo",
			Terminal:  "Main Terminal, Gate D",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:30",
		},
		{
			Name:      "No1 Lounge Oslo",
			Terminal:  "Main Terminal, Airside",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:00",
		},
	},
	// ── Middle East ─────────────────────────────────────────────────────────
	"DXB": {
		{
			Name:      "G-Force Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Marhaba Lounge",
			Terminal:  "Terminal 3, Concourse B",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Prayer room"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Al Majlis Lounge (dnata)",
			Terminal:  "Terminal 3, Concourse C",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Ahlan Business Lounge",
			Terminal:  "Terminal 3, Concourse A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Showers", "Prayer room"},
			OpenHours: "24 hours",
		},
		// Emirates airline lounges (NOT Priority Pass)
		{
			Name:      "Emirates Business Class Lounge",
			Terminal:  "Terminal 3, Concourse B",
			Cards:     []string{"Emirates Business Class", "Emirates Skywards Gold", "Emirates Skywards Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa", "Barber"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Emirates First Class Lounge",
			Terminal:  "Terminal 3, Concourse A",
			Cards:     []string{"Emirates First Class", "Emirates Skywards Platinum"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Spa", "Cigar bar", "Shoe shine"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Emirates Business Class Lounge",
			Terminal:  "Terminal 3, Concourse C",
			Cards:     []string{"Emirates Business Class", "Emirates Skywards Gold", "Emirates Skywards Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
	},
	"DOH": {
		{
			Name:      "Qatar Airways Al Maha Arrivals Lounge",
			Terminal:  "Hamad International, Arrivals",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Qatar Airways Premium Terminal",
			Terminal:  "Hamad International",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa", "Sleeping suites"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Oryx Lounge",
			Terminal:  "Hamad International, Concourse D",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		// Qatar Airways airline lounges (NOT Priority Pass)
		{
			Name:      "Qatar Airways Al Mourjan Business Lounge",
			Terminal:  "Hamad International, near Gate A2",
			Cards:     []string{"Qatar Airways Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Qatar Privilege Club Gold", "Qatar Privilege Club Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Restaurant", "Bar", "Showers", "Quiet rooms", "Family area", "Games room"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Qatar Airways Al Mourjan Business Lounge — The Garden",
			Terminal:  "Hamad International, near Gate B",
			Cards:     []string{"Qatar Airways Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Qatar Privilege Club Gold", "Qatar Privilege Club Platinum"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Bar", "Showers", "Indoor garden", "Deli", "Quiet rooms"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Qatar Airways Al Safwa First Lounge",
			Terminal:  "Hamad International, near Gate A",
			Cards:     []string{"Qatar Airways First Class", "Oneworld Emerald", "Qatar Privilege Club Platinum"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Spa", "Showers", "Private suites", "Family lounge"},
			OpenHours: "24 hours",
		},
	},
	"IST": {
		{
			Name:      "Turkish Airlines Lounge (Domestic)",
			Terminal:  "Istanbul Airport, Domestic",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Turkish Airlines Lounge (International)",
			Terminal:  "Istanbul Airport, International",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Library", "Golf simulator"},
			OpenHours: "24 hours",
		},
		{
			Name:      "IST Select Lounge",
			Terminal:  "Istanbul Airport, International",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
	},
	// ── Asia-Pacific ─────────────────────────────────────────────────────────
	"SIN": {
		{
			Name:      "Blossom Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Napping pods"},
			OpenHours: "24 hours",
		},
		{
			Name:      "SATS Premier Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "SATS Premier Lounge",
			Terminal:  "Terminal 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "24 hours",
		},
		{
			Name:      "The Haven",
			Terminal:  "Terminal 1 (Jewel)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Napping pods"},
			OpenHours: "24 hours",
		},
		// Singapore Airlines airline lounges (NOT Priority Pass)
		{
			Name:      "Singapore Airlines SilverKris Business Class Lounge",
			Terminal:  "Terminal 3",
			Cards:     []string{"SQ Business Class", "Star Alliance Gold", "KrisFlyer Elite Gold", "KrisFlyer PPS Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Workstations"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Singapore Airlines SilverKris First Class Lounge",
			Terminal:  "Terminal 3",
			Cards:     []string{"SQ First Class", "Star Alliance Gold", "KrisFlyer PPS Club", "KrisFlyer Solitaire PPS"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Private rooms"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Singapore Airlines The Private Room",
			Terminal:  "Terminal 3",
			Cards:     []string{"SQ Suites Class", "SQ First Class", "KrisFlyer Solitaire PPS"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Private suites"},
			OpenHours: "24 hours",
		},
	},
	"NRT": {
		{
			Name:      "IASS Superior Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "06:30–21:30",
		},
		{
			Name:      "Sky Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "07:00–21:00",
		},
		{
			Name:      "Narita Airport IASS Executive Lounge No.2",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "07:00–22:00",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "ANA Lounge",
			Terminal:  "Terminal 1, Satellite 4F",
			Cards:     []string{"ANA Business Class", "Star Alliance Gold", "ANA Super Flyers Card", "ANA Diamond"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Noodle bar"},
			OpenHours: "07:00–21:30",
		},
		{
			Name:      "JAL Sakura Lounge",
			Terminal:  "Terminal 2, Main Building 3F",
			Cards:     []string{"JAL Business Class", "Oneworld Sapphire", "Oneworld Emerald", "JAL Global Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Massage chairs"},
			OpenHours: "07:30–21:30",
		},
		{
			Name:      "JAL First Class Lounge",
			Terminal:  "Terminal 2, Main Building 3F",
			Cards:     []string{"JAL First Class", "Oneworld Emerald", "JAL Diamond", "JAL JGC Premier"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Sushi bar", "Champagne bar", "Showers", "Massage"},
			OpenHours: "07:30–21:30",
		},
	},
	"HND": {
		{
			Name:      "Sky Lounge Annex",
			Terminal:  "Terminal 3 (International)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "06:00–21:00",
		},
		{
			Name:      "TIAT Sky Lounge South",
			Terminal:  "Terminal 3 (International)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
	},
	"ICN": {
		{
			Name:      "Matina Lounge",
			Terminal:  "Terminal 1, Concourse A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Sky Hub Lounge",
			Terminal:  "Terminal 1, Concourse B",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Lotte Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "Korean Air Prestige Class Lounge",
			Terminal:  "Terminal 2, Concourse",
			Cards:     []string{"Korean Air Business Class", "Korean Air First Class", "SkyTeam Elite Plus", "Korean Air Morning Calm Premium"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Napping area", "Workstations"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Korean Air First Class Lounge",
			Terminal:  "Terminal 2, Concourse",
			Cards:     []string{"Korean Air First Class", "Korean Air Morning Calm Premium", "SkyTeam Elite Plus"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Bar", "Showers", "Private suites", "Spa"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Asiana Business Class Lounge",
			Terminal:  "Terminal 1, Concourse A",
			Cards:     []string{"Asiana Business Class", "Asiana First Class", "Star Alliance Gold", "Asiana Diamond Plus", "Asiana Diamond"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Napping area"},
			OpenHours: "24 hours",
		},
	},
	"HKG": {
		{
			Name:      "Plaza Premium Lounge (East Hall)",
			Terminal:  "Terminal 1, East Hall",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Plaza Premium Lounge (West Hall)",
			Terminal:  "Terminal 1, West Hall",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "BITA Lounge",
			Terminal:  "Terminal 1, Level 7",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		// Cathay Pacific airline lounges (NOT Priority Pass)
		{
			Name:      "Cathay Pacific The Pier Business Class Lounge",
			Terminal:  "Terminal 1, near Gate 65",
			Cards:     []string{"Cathay Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Cathay Marco Polo Gold", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Noodle bar", "Teahouse", "Bar", "Showers", "Day suites"},
			OpenHours: "05:30–00:30",
		},
		{
			Name:      "Cathay Pacific The Pier First Class Lounge",
			Terminal:  "Terminal 1, near Gate 65",
			Cards:     []string{"Cathay First Class", "Oneworld Emerald", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Day suites", "Spa"},
			OpenHours: "05:30–00:30",
		},
		{
			Name:      "Cathay Pacific The Wing Business Class Lounge",
			Terminal:  "Terminal 1, near Gate 1",
			Cards:     []string{"Cathay Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Cathay Marco Polo Gold", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Noodle bar", "Bar", "Showers"},
			OpenHours: "05:30–00:30",
		},
		{
			Name:      "Cathay Pacific The Wing First Class Lounge",
			Terminal:  "Terminal 1, near Gate 1",
			Cards:     []string{"Cathay First Class", "Oneworld Emerald", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Cabanas"},
			OpenHours: "05:30–00:30",
		},
	},
	"BKK": {
		{
			Name:      "Miracle Lounge (Concourse D)",
			Terminal:  "Suvarnabhumi, Concourse D",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Miracle Lounge (Concourse G)",
			Terminal:  "Suvarnabhumi, Concourse G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Thai Airways Royal Orchid Lounge",
			Terminal:  "Suvarnabhumi, Level 4",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Coral Executive Lounge",
			Terminal:  "Don Mueang, Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "05:00–23:00",
		},
		// Thai Airways airline lounges (NOT Priority Pass)
		{
			Name:      "Thai Airways Royal Silk Lounge",
			Terminal:  "Suvarnabhumi, Concourse D",
			Cards:     []string{"Thai Business Class", "Star Alliance Gold", "Royal Orchid Plus Gold", "Royal Orchid Plus Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa", "Napping area"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Thai Airways Royal First Lounge",
			Terminal:  "Suvarnabhumi, Concourse D",
			Cards:     []string{"Thai First Class", "Star Alliance Gold", "Royal Orchid Plus Platinum"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Spa", "Private suites"},
			OpenHours: "24 hours",
		},
	},
	"PEK": {
		{
			Name:      "Air China First Class Lounge",
			Terminal:  "Terminal 3, Concourse E",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "CNAC Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "07:00–22:00",
		},
		{
			Name:      "VIP Lounge (Capital Airlines)",
			Terminal:  "Terminal 3, Concourse D",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
	},
	"PVG": {
		{
			Name:      "Longemont Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Dragonair Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "06:00–23:00",
		},
		{
			Name:      "VIP Lounge (China Eastern)",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar"},
			OpenHours: "06:00–23:00",
		},
	},
	"SYD": {
		{
			Name:      "Qantas International Business Lounge",
			Terminal:  "Terminal 1 (International)",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 1 (International)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "No1 Lounge Sydney",
			Terminal:  "Terminal 1 (International)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–21:30",
		},
	},
	"MEL": {
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 2 (International)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Qantas International Business Lounge",
			Terminal:  "Terminal 2 (International)",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:30–21:30",
		},
	},
	// ── Americas ────────────────────────────────────────────────────────────
	"JFK": {
		{
			Name:      "The Centurion Lounge",
			Terminal:  "Terminal 4",
			Cards:     []string{"Amex Centurion", "Amex Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 4",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar"},
			OpenHours: "05:30–22:30",
		},
		{
			Name:      "Wingtips Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "04:30–23:00",
		},
		{
			Name:      "Club at JFK",
			Terminal:  "Terminal 5",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:00",
		},
	},
	"LAX": {
		{
			Name:      "The Centurion Lounge",
			Terminal:  "Terminal 4",
			Cards:     []string{"Amex Centurion", "Amex Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "The Club at LAX",
			Terminal:  "Tom Bradley International (TBIT)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Tom Bradley International (TBIT)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Star Alliance Lounge",
			Terminal:  "Tom Bradley International (TBIT)",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "Delta Sky Club",
			Terminal:  "Terminal 2",
			Cards:     []string{"Delta One", "Delta Business Class", "SkyTeam Elite Plus", "Delta SkyMiles Diamond", "Delta SkyMiles Platinum", "Delta Sky Club Membership"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Sky Deck"},
			OpenHours: "04:30–23:00",
		},
		{
			Name:      "Delta Sky Club",
			Terminal:  "Terminal 3",
			Cards:     []string{"Delta One", "Delta Business Class", "SkyTeam Elite Plus", "Delta SkyMiles Diamond", "Delta SkyMiles Platinum", "Delta Sky Club Membership"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "04:30–23:00",
		},
		{
			Name:      "United Polaris Lounge",
			Terminal:  "Terminal 7",
			Cards:     []string{"United Business Class", "United First Class", "Star Alliance Gold", "United MileagePlus 1K", "United MileagePlus Global Services"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Bar", "Showers", "Daybeds", "Workstations"},
			OpenHours: "06:00–23:00",
		},
	},
	"SFO": {
		{
			Name:      "The Centurion Lounge",
			Terminal:  "Terminal 3",
			Cards:     []string{"Amex Centurion", "Amex Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		{
			Name:      "United Club",
			Terminal:  "Terminal 3, Gate F",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "The Club at SFO",
			Terminal:  "International Terminal G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–23:00",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "United Polaris Lounge",
			Terminal:  "International Terminal G",
			Cards:     []string{"United Business Class", "United First Class", "Star Alliance Gold", "United MileagePlus 1K", "United MileagePlus Global Services"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Bar", "Showers", "Daybeds", "Workstations"},
			OpenHours: "06:00–23:30",
		},
	},
}
