package calendar

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"time"

	"github.com/MikkoParkkola/trvl/internal/models"
)

// ScheduleICSInput describes a Leave-By schedule to render as a calendar event.
type ScheduleICSInput struct {
	Date          string // flight date, YYYY-MM-DD
	AirportCode   string // departure airport IATA
	DepartureTime string // flight departure local time, HH:MM
	ReminderMin   int    // VALARM lead time before leave-home (default 30)
	Schedule      models.ScheduleTimeline
}

// ScheduleICS renders a Leave-By timeline as RFC 5545 iCalendar text: a single
// "Leave home" VEVENT at the leave-by time carrying a display VALARM (the
// anxiety-killing reminder) and the full timeline + assumptions in its
// description. Times are floating local (no Z/TZID) so they import as the local
// wall-clock the scheduler computed. Pure: no I/O.
func ScheduleICS(in ScheduleICSInput) (string, error) {
	if in.Date == "" || in.Schedule.LeaveHomeBy == "" {
		return "", fmt.Errorf("schedule ICS requires a date and a computed leave_home_by time")
	}
	leaveStart, err := time.ParseInLocation("2006-01-02 15:04", in.Date+" "+in.Schedule.LeaveHomeBy, time.Local)
	if err != nil {
		return "", fmt.Errorf("invalid date/leave_home_by: %w", err)
	}
	reminder := in.ReminderMin
	if reminder <= 0 {
		reminder = 30
	}

	var b strings.Builder
	now := time.Now().UTC()
	writeLine(&b, "BEGIN:VCALENDAR")
	writeLine(&b, "VERSION:2.0")
	writeLine(&b, "PRODID:"+ProductID)
	writeLine(&b, "CALSCALE:GREGORIAN")
	writeLine(&b, "METHOD:PUBLISH")
	writeLine(&b, "X-WR-CALNAME:"+escapeText("trvl — Leave-by for "+in.AirportCode))

	writeLine(&b, "BEGIN:VEVENT")
	h := sha256.New()
	_, _ = fmt.Fprintf(h, "%s|%s|%s|%s", in.Date, in.AirportCode, in.DepartureTime, in.Schedule.LeaveHomeBy)
	writeLine(&b, fmt.Sprintf("UID:trvl-leaveby-%s@trvl.local", hex.EncodeToString(h.Sum(nil))[:12]))
	writeLine(&b, "DTSTAMP:"+now.Format("20060102T150405Z"))
	writeLine(&b, "DTSTART:"+leaveStart.Format("20060102T150405"))
	writeLine(&b, "DTEND:"+leaveStart.Add(time.Duration(reminder)*time.Minute).Format("20060102T150405"))
	writeLine(&b, "SUMMARY:"+escapeText(fmt.Sprintf("🚪 Leave home for %s (flight %s)", in.AirportCode, in.DepartureTime)))
	writeLine(&b, "DESCRIPTION:"+escapeText(scheduleDescription(in)))
	writeLine(&b, "STATUS:CONFIRMED")

	// VALARM: display reminder before leave-home — the core value of this event.
	writeLine(&b, "BEGIN:VALARM")
	writeLine(&b, "ACTION:DISPLAY")
	writeLine(&b, fmt.Sprintf("TRIGGER:-PT%dM", reminder))
	writeLine(&b, "DESCRIPTION:"+escapeText(fmt.Sprintf("Leave in %d min for %s", reminder, in.AirportCode)))
	writeLine(&b, "END:VALARM")

	writeLine(&b, "END:VEVENT")
	writeLine(&b, "END:VCALENDAR")
	return b.String(), nil
}

func scheduleDescription(in ScheduleICSInput) string {
	var parts []string
	for _, row := range in.Schedule.Steps {
		parts = append(parts, row.Time+"  "+row.Text)
	}
	if in.Schedule.Confidence != "" {
		parts = append(parts, "Confidence: "+in.Schedule.Confidence)
	}
	if len(in.Schedule.Assumptions) > 0 {
		parts = append(parts, "Assumptions: "+strings.Join(in.Schedule.Assumptions, "; "))
	}
	if in.Schedule.Fallback != "" {
		parts = append(parts, "Fallback: "+in.Schedule.Fallback)
	}
	parts = append(parts, "Generated by trvl (https://github.com/MikkoParkkola/trvl)")
	return strings.Join(parts, "\n")
}
